### ISSUE TITLE
Missing dependency in requirements.in

### ISSUE THREAD

**Issue by awecx** [JulienPalard/powrap#69]
Looks like install dependency _tqdm_ defined in _setup.cfg_ is missing from _requirements.in_ file.
It is however included 'by sheer luck' in _requirements.dev_ as it is a dependency of twine.
On a side note, _blake_ is duplicated.

**Comment by JulienPalard** [comment]
I'm not fan of copy-pasting things, I don't want to maintain two lists of requirements, they'll get out of sync.

Install requirements should stay in install_requires, and developement requirements should stay in `requirements-dev.txt`.

I bet you've found a missing `tqdm` because you followed the `Contributing` section in the readme, if so, what about adding a `pip install -e .` in it? It would provide the developer with a working `powrap` (with `install_requires` satisfied).

The only "bad" part of it is: we're not pinning install requirements (for developer uses, not for end users, so just to reproduce bugs from a dev env to another dev env). If we need to pin them we could easily `pip-compile setup.py`. Then we could also add `-r requirements.txt` in `requirements-dev.in` to have a common, full, pinned, list of dependencies, which is nice to reproduce bugs (from a dev env to another dev env only, again, not from a user env to a dev env, as a user can have different set of version installed, a user don't use a specific venv for each command), but I think it's too convoluted for a small project.

**Comment by JulienPalard** [comment]
Ohh got it, I have a typo in the README file, it tells to install `requirements-dev.in` instead of `requirements-dev.txt` :(
